; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
extra_configs =
	secret.ini

[env:board-esp8266]
platform = espressif8266
board = nodemcuv2
framework = arduino
build_flags =
	-std=c++2a
	-I src/common
	-D ESP8266=1
	-D SERIAL_BAUD_RATE=9600
	-D LOG_LEVEL=4
	-D INFLUX_HOST=\"${secret.influx_host}\"
	-D INFLUX_PORT=${secret.influx_port}
	-D SYSLOG_HOST=\"${secret.syslog_host}\"
	-D SYSLOG_PORT=${secret.syslog_port}

build_unflags =
	-std=gnu++17
lib_deps =
	ESP8266WiFi@^1.0
	ESP8266WebServer@^1.0
	OneWire@^2.3.7
	DallasTemperature@^3.11.0
	EspSoftwareSerial
	mandulaj/PZEM-004T-v30 @ ^1.1.2
	tzapu/WiFiManager@^2.0.17
	https://github.com/piolibs/console.git
	https://github.com/piolibs/reporter.git
	https://github.com/piolibs/config.git
	https://github.com/piolibs/checksum.git
upload_speed = 115200
monitor_speed = 9600
monitor_filters = default
monitor_rts = 0
monitor_dtr = 0

[env:board-esp32]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
build_flags = -D ESP32=1
lib_deps =
	OneWire@^2.3.7
	DallasTemperature@^3.11.0
	mandulaj/PZEM-004T-v30 @ ^1.1.2
upload_speed = 115200
monitor_speed = 115200
